#!/usr/bin/env python3
"""AutoPaper for Windows: the English strings, written to AutoPaper/Strings/en-US/Resources.resw.

One place for the app's words (AudioPaper's voice: plain, specific, short; Windows sentence case). Keys with a
dot are x:Uid properties (Uid.Property, or Uid.[using:Namespace]Class.Property for attached properties); keys
with an underscore are read in code (Loc.Get / Loc.Format, {0}-style placeholders).

    python3 apps/windows/tools/strings.py
"""
from pathlib import Path
from xml.sax.saxutils import escape

OUT = Path(__file__).resolve().parent.parent / "AutoPaper" / "Strings" / "en-US" / "Resources.resw"
NAME = "[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name"
HELP = "[using:Microsoft.UI.Xaml.Automation]AutomationProperties.HelpText"
KEYS = "[using:Microsoft.UI.Xaml.Automation]AutomationProperties.AcceleratorKey"
TIP = "[using:Microsoft.UI.Xaml.Controls]ToolTipService.ToolTip"

S = {
    # ── Navigation ──
    "NavNow.Content": "Now",
    "NavMoods.Content": "Moods",
    "NavHistory.Content": "History",
    "NavConsole.Content": "Console",
    "Nav_SettingsTip": "Settings (Ctrl+,)",
    "Nav_SettingsKeys": "Ctrl+,",

    # ── Console: local dates → runs → outcomes and the exact provider trace ──
    "ConsoleTitle.Text": "Console",
    "ConsoleOverview.Header": "Overview",
    "Console_Runs": "Runs",
    "Console_SuccessRate": "Success rate",
    "Console_AverageRun": "Average run time",
    "Console_DailyRuns": "Daily runs (UTC)",
    "Console_Outcomes": "Outcomes",
    "Console_ChartSummary": "Daily runs in UTC: {0} runs. Show as table for the outcome counts.",
    "Console_NoChartData": "No runs yet",
    "ConsoleModelTimings.Text": "Average call time",
    "Console_NoTimings": "No call timings recorded",
    "Console_JobWriting": "Writing",
    "Console_JobPainting": "Painting",
    "Console_ModelJob": "{0} · {1}",
    "Console_CallTime": "{0} · {1} calls",
    "Console_Seconds": "{0} s",
    f"ConsoleCommands.{NAME}": "Console commands",
    "ConsoleRefresh.Label": "Refresh",
    "ConsoleCopy.Label": "Copy details",
    "ConsoleExport.Label": "Export JSON…",
    "ConsoleClear.Label": "Clear console…",
    "ConsoleRunsHeading.Text": "Dates and runs",
    f"ConsoleRunTree.{NAME}": "Dates and runs",
    f"ConsoleRunTree.{HELP}": "Expand a date to see its runs. Select a run to read its outcome and exact requests and responses.",
    "ConsoleEmpty.Text": "No runs yet",
    "ConsoleOlder.Content": "Load older runs",
    "ConsoleChooseRun.Text": "Select a run",
    "ConsoleNoEvents.Text": "No provider events recorded",
    "ConsoleStatus_Running": "Running",
    "ConsoleStatus_Succeeded": "Completed",
    "ConsoleStatus_Failed": "Failed",
    "ConsoleStatus_Blocked": "Blocked",
    "ConsoleStatus_Cancelled": "Cancelled",
    "ConsoleStatus_Interrupted": "Interrupted",
    "ConsoleTrigger_Scheduled": "Scheduled",
    "ConsoleTrigger_Manual": "New wallpaper now",
    "ConsoleTrigger_DislikeReplace": "Replace a disliked wallpaper",
    "ConsoleTrigger_EchoRequest": "Make an echo",
    "Console_ProviderModel": "{0} · {1}",
    "Console_Row": "{0} {1} · {2} · {3}",
    "Console_Selection": "{0} · {1}",
    "Console_Started": "Started: {0}, {1}",
    "Console_Trigger": "Requested by: {0}",
    "Console_Writing": "Writing: {0}",
    "Console_Painting": "Painting: {0}",
    "Console_Surprise": "Surprise: {0}%",
    "Console_Cost": "Estimated cost recorded: {0}",
    "Console_Duration": "Duration: {0} seconds",
    "Console_Keywords": "Keywords: {0}",
    "Console_None": "None",
    "Console_Id": "Run ID: {0}",
    "Console_GenerationId": "Wallpaper ID: {0}",
    "Console_EventDetail": "{0}, {1} details",
    "Console_Refreshed": "Console refreshed.",
    "Console_Copied": "Run details copied.",
    "Console_Exported": "Run details exported.",
    "Console_Json": "JSON run report",
    "Console_ClearTitle": "Clear console?",
    "Console_ClearBody": "This deletes the local run details, including recorded prompts and responses. Wallpapers, memory, settings and this month's spending stay. Console can't be cleared while a wallpaper is being made.",
    "Console_ClearConfirm": "Clear console",
    "Console_Cleared": "Console cleared.",
    "Console_NotRecorded": "Not recorded for this wallpaper.",
    "GalleryPrompt.Header": "Image prompt",
    "GalleryOpenConsole.Content": "Open console for run details",
    "BudgetBlockedNotice.Title": "New wallpapers are blocked by the budget",
    "BudgetNoticeLink.Content": "Open budget settings",

    # ── Now ──
    "NowEmptyTitle.Text": "No wallpaper yet",
    "NowEmptyBody.Text": "Choose New wallpaper now, or wait for the next one. AutoPaper makes them from your keywords.",
    "NowOpenProblem.Title": "AutoPaper can't start",
    f"NowLike.{NAME}": "Like",
    f"NowLike.{HELP}": "Tell AutoPaper you like this wallpaper. Choose again to clear it.",
    "NowLikeText.Text": "Like",
    f"NowDislike.{NAME}": "Dislike",
    f"NowDislike.{HELP}": "Tell AutoPaper you don't like it. It may make a new one straight away.",
    "NowDislikeText.Text": "Dislike",
    "NowTitle.Text": "Now",
    f"NowCommands.{NAME}": "Wallpaper commands",
    f"NowProgress.{NAME}": "Making a wallpaper",
    # Now's reload/stop (and a mood's), like a browser's: one button that changes while a wallpaper is being made.
    "MakeOrStop_Make": "New wallpaper now",
    "MakeOrStop_UseAndMake": "Use this mood and make a new wallpaper",
    "MakeOrStop_Stop": "Stop",
    "MakeOrStop_MakeTip": "{0} (Ctrl+R)",
    "MakeOrStop_StopTip": "Stop making this wallpaper (Esc)",
    "MakeOrStop_MakeKeys": "Ctrl+R",
    "MakeOrStop_StopKeys": "Escape",
    # Which models made a wallpaper: "Written by … · Painted by … · 3840×2160 · about $0.04".
    "Provenance_Who": "{0} ({1})",
    "Provenance_Written": "Written by {0}",
    "Provenance_Painted": "Painted by {0}",
    "Provenance_SizeSpoken": "{0} by {1}",
    "Provenance_Cost": "about {0}",
    "Provenance_PaintedHelp": "Opens Providers in Settings, where you choose who paints.",
    "NowOwnWallpaper.Text": "Your own wallpaper is showing. AutoPaper's next new wallpaper replaces it.",
    "NowOpenMoods.Content": "Open moods",
    # After Clear history: the desktop keeps its picture until the next new wallpaper.
    "Now_ClearedTitle": "History is empty",
    "Now_ClearedBody": "The desktop keeps its picture until the next new wallpaper. Choose New wallpaper now, or wait for the next one.",
    "NarrowKeywords.Message": "Your keywords are narrow, so new ideas are getting hard to find. Add some Maybes or raise Surprise for more variety.",

    # ── Moods: list › detail (the keyword rows below are the detail's) ──
    "MoodsTitle.Text": "Moods",
    "MoodsIntro.Text": "Each mood has its own keywords and Surprise. New wallpapers use the current one.",
    "MoodNew.Label": "New mood",
    f"MoodNew.{NAME}": "New mood",
    f"MoodNew.{KEYS}": "Ctrl+N",
    f"MoodNew.{TIP}": "New mood (Ctrl+N)",
    f"MoodList.{NAME}": "Moods",
    f"MoodList.{HELP}": "Press Enter or double-click to use a mood. Drag, or press Alt+Up or Alt+Down, to reorder. Right-click or press Shift+F10 for more.",
    "MoodMenuUse.Text": "Use",
    "MoodMenuDuplicate.Text": "Duplicate",
    "MoodMenuRename.Text": "Rename…",
    "MoodMenuMoveUp.Text": "Move up",
    "MoodMenuMoveDown.Text": "Move down",
    "MoodMenuDelete.Text": "Delete…",
    "MoodCurrentBadge.Text": "Current",
    "MoodUseButton.Content": "Use",
    f"MoodNameBox.{NAME}": "Mood name",
    "MoodNameBox.PlaceholderText": "Name this mood",
    "MoodNameBox.Header": "Mood name",
    "MoodCurrentLine.Text": "Current mood",
    "MoodUseThis.Content": "Use this mood",
    f"MoodUseThis.{HELP}": "New wallpapers use its keywords and Surprise. Nothing is made until you ask or the next one is due.",
    "MoodKeywordsTitle.Text": "Keywords",
    "MoodRecentTitle.Text": "Made in this mood",
    "MoodRecentNone.Text": "None yet. Wallpapers made while this mood is current appear here.",
    "MoodShowInHistory.Content": "Show all in History",
    f"MoodDelete.{NAME}": "Delete mood…",
    "MoodDeleteText.Text": "Delete mood…",
    "Mood_NotRenamed": "{0} keeps its name. {1}",
    f"MoodCommands.{NAME}": "Mood commands",
    "Mood_InUse": "Current mood",
    "Mood_NotInUse": "Not in use",
    "Mood_SurpriseLine": "Surprise: {0} ({1}%)",
    "Mood_DeleteNote": "Its wallpapers stay in History.",
    "Mood_MadeIn": "Made in {0}",
    "Mood_RecentName": "Wallpapers made in {0}",
    "Thumbnail_Help": "Shows it on the desktop. Right-click or press Shift+F10 for more.",
    "Thumbnail_Tip": "{0}\nShow on desktop",
    # What moods have made (mood_stats): the summary of every mood and a mood's header.
    "MoodsSummaryTitle.Text": "Your moods",
    "MoodsMostUsed.Text": "Most used",
    "Stat_Moods": "Moods",
    "Stat_MoodsSpoken": "{0} moods",
    "Stat_MoodsSpokenOne": "{0} mood",
    "Stat_Wallpapers": "Wallpapers",
    "Stat_Liked": "Liked",
    "Stat_Echoes": "Echoes",
    "Stat_EchoesSpoken": "{0} echoes",
    "Stat_EchoesSpokenOne": "{0} echo",
    "Stat_LastMade": "Last made",
    "Stat_LastMadeSpoken": "Last made: {0}",
    "Mood_NothingMade": "Nothing made yet",
    "Mood_Liked": "{0} liked",
    "Mood_LastMade": "last made {0}",
    "Mood_NotYet": "Not yet",
    "Mood_KeywordGroup": "{0}: {1}",
    "Mood_Breakdown": "{0} Must · {1} Maybe · {2} Avoid keywords",
    "Mood_BreakdownOne": "{0} Must · {1} Maybe · {2} Avoid keyword",
    "Mood_LatestOne": "Latest wallpaper: {0}",
    "Mood_LatestMany": "Latest wallpapers: {0}",
    "MoodCard_OpenHelp": "Shows its keywords and Surprise.",
    "MoodCard_OpenTip": "Show {0}",
    "MoodCard_UseTip": "Make this the current mood. Nothing changes until the next wallpaper.",
    "MoodCard_WallpaperUnit": "wallpaper",
    "MoodCard_WallpapersUnit": "wallpapers",
    # When, in a sentence ("last made 3 hours ago").
    "Relative_JustNow": "just now",
    "Relative_MinuteAgo": "a minute ago",
    "Relative_MinutesAgo": "{0} minutes ago",
    "Relative_HourAgo": "an hour ago",
    "Relative_HoursAgo": "{0} hours ago",
    "Relative_Yesterday": "yesterday",
    "Relative_DaysAgo": "{0} days ago",
    "Relative_WeekAgo": "a week ago",
    "Relative_WeeksAgo": "{0} weeks ago",
    "Relative_On": "on {0}",
    # The summary's chart (activity): wallpapers per day, stacked by mood.
    "Activity_Title": "Wallpapers, last 30 days",
    "Activity_None": "No wallpapers in the last {0} days.",
    "Activity_Footnote": "{0} in the last {1} days. Kept on this PC only.",
    "Activity_DayPart": "{0} {1}",
    "Activity_Other": "Other moods",
    "Activity_Legend": "Legend: {0}",
    "Activity_ShowTable": "Show as table",
    "Activity_TableHint": "Show as table, below, has each day's numbers.",
    "Activity_TableDay": "Day",
    "Activity_TableMoods": "Moods",
    "Activity_TableWallpapers": "Wallpapers",
    "Mood_NewName": "New mood",
    # Duplicate's name: "Rainy beach copy" (then "Rainy beach copy 2").
    "Mood_CopySuffix": " copy",
    "Mood_NoKeywords": "No keywords yet",
    # An Avoid in a mood's summary: what's left out.
    "Mood_AvoidShort": "no {0}",
    "Mood_SpokenCurrent": "{0}, current mood",
    "Mood_RowName": "{0}, {1}",
    "Mood_UseName": "Use {0}",
    "Mood_Using": "Now using {0}.",
    "Mood_AlreadyCurrent": "{0} is already the current mood.",
    "Mood_Created": "Added {0}.",
    "Mood_Duplicated": "Duplicated as {0}.",
    "Mood_Renamed": "Renamed to {0}.",
    "Mood_Deleted": "Deleted {0}.",
    "Mood_DeletedCurrent": "Deleted {0}. {1} is the current mood now.",
    "MoodDelete_Title": "Delete “{0}”?",
    "MoodDelete_Body": "Its keywords and Surprise are deleted. Wallpapers made in it stay in History.",
    "MoodDelete_Confirm": "Delete",
    "KeywordsIntro.Text": "A few words for what you'd like to see. Must: always in the scene. Maybe: some of the time. Avoid: never.",
    "KeywordAddBox.PlaceholderText": "Add a keyword",
    f"KeywordAddBox.{NAME}": "Add a keyword",
    f"KeywordAddBox.{HELP}": "Press Enter to add it as a Must.",
    "KeywordAddButton.Content": "Add",
    f"KeywordAddButton.{HELP}": "Adds the keyword as a Must.",
    "KeywordsEmpty.Text": "No keywords yet. Add a few, like rain, ruins, night or blue.",
    f"KeywordList.{NAME}": "Your keywords",
    f"KeywordList.{HELP}": "Drag to reorder, or press Alt+Up or Alt+Down. Right-click or press Shift+F10 for more.",
    "KeywordMoveUp.Text": "Move up",
    "KeywordMoveDown.Text": "Move down",
    "KeywordRemove.Text": "Remove",
    f"KeywordRemoveButton.{TIP}": "Remove",
    "WeightMustItem.Content": "Must",
    "WeightMaybeItem.Content": "Maybe",
    "WeightAvoidItem.Content": "Avoid",
    "SurpriseTitle.Text": "Surprise",
    "SurpriseIntro.Text": "How freely AutoPaper reads this mood's keywords.",
    "SurpriseFaithfulEnd.Text": "Faithful",
    "SurpriseWildEnd.Text": "Wild",
    f"SurpriseSlider.{NAME}": "Surprise",
    "Keyword_Spoken": "{0}, {1}",
    "Keyword_EditName": "Keyword",
    "Keyword_WeightName": "Weight for {0}",
    "Keyword_RemoveName": "Remove {0}",
    "Keyword_Duplicate": "{0} is already in your keywords, as {1}.",
    "Keyword_Added": "Added {0}.",
    "Keyword_Removed": "Removed {0}.",
    "Keyword_Renamed": "Renamed to {0}.",
    "Keyword_Moved": "Moved {0} to position {1} of {2}.",
    "Weight_Must": "Must",
    "Weight_Maybe": "Maybe",
    "Weight_Avoid": "Avoid",
    "Surprise_Band": "{1} ({0}%)",
    "Surprise_Spoken": "{0} percent, {1}",
    "Surprise_Faithful": "Faithful",
    "Surprise_FaithfulDetail": "Each keyword as anyone would picture it, in a believable scene.",
    "Surprise_Fresh": "Fresh",
    "Surprise_FreshDetail": "Believable scenes, each with one unexpected choice of viewpoint, light, season or style.",
    "Surprise_Adventurous": "Adventurous",
    "Surprise_AdventurousDetail": "Free interpretations, with unexpected settings, scales, eras and styles.",
    "Surprise_Wild": "Wild",
    "Surprise_WildDetail": "Keywords as loose inspiration for dreamlike scenes in bold styles.",
    "ResetLearned_Title": "Reset what AutoPaper has learned?",
    "ResetLearned_Body": "It forgets the likes and dislikes it has learned from your ratings. Your ratings stay on each wallpaper, and memory still avoids repeats.",
    "ResetLearned_Confirm": "Reset",
    "ResetLearned_Done": "AutoPaper has forgotten what it learned.",
    "Dialog_Cancel": "Cancel",
    "Dialog_Close": "Close",

    # ── History ──
    "HistoryTitle.Text": "History",
    f"HistoryFilter.{NAME}": "Filter wallpapers",
    f"HistoryMoodFilter.{NAME}": "Mood",
    "HistoryMoodFilterLabel.Text": "Mood",
    "History_AllMoods": "All moods",
    "HistoryFilterAll.Text": "All",
    "HistoryFilterLiked.Text": "Liked",
    "HistoryFilterDisliked.Text": "Disliked",
    "HistoryFilterEchoes.Text": "Echoes",
    f"HistoryView.{NAME}": "View",
    "HistoryViewGrid.Text": "Grid",
    "HistoryViewGallery.Text": "Gallery",
    f"HistoryFilmstrip.{NAME}": "Wallpapers",
    f"HistoryFilmstrip.{HELP}": "Use the arrow keys to move along. Press Enter or double-click to show a wallpaper on the desktop. Right-click or press Shift+F10 for more actions.",
    "GalleryLineage.Content": "Show original and echoes",
    "GalleryShowOnDesktop.Content": "Show on desktop",
    "GalleryMakeEcho.Content": "Make an echo",
    "GalleryShowInExplorer.Content": "Show in File Explorer",
    "GalleryDelete.Content": "Delete…",
    "Gallery_Made": "Made {0}",
    "Gallery_Mood": "Mood: {0}",
    "Gallery_Keywords": "Keywords: {0}",
    f"HistoryGrid.{NAME}": "Wallpapers",
    f"HistoryGrid.{HELP}": "Press Enter or double-click to show a wallpaper on the desktop. Right-click or press Shift+F10 for more actions.",
    "HistoryShowOnDesktop.Text": "Show on desktop",
    "HistoryLike.Text": "Like",
    "HistoryDislike.Text": "Dislike",
    "HistoryMakeEcho.Text": "Make an echo",
    "HistoryLineage.Text": "Show original and echoes",
    "HistoryShowInExplorer.Text": "Show in File Explorer",
    "HistoryDelete.Text": "Delete…",
    "BadgeLiked.Text": "Liked",
    "BadgeDisliked.Text": "Disliked",
    "BadgeEcho.Text": "Echo",
    "History_Made": "{0}, {1}",
    "History_MoreName": "More actions for {0}",
    "History_Empty": "No wallpapers yet. They appear here as AutoPaper makes them.",
    "History_EmptyLiked": "No liked wallpapers yet.",
    "History_EmptyDisliked": "No disliked wallpapers.",
    "History_EmptyEchoes": "No echoes yet. An idea comes back as an echo once its quiet period has passed, or when you choose Make an echo.",
    "History_EmptyMood": "Nothing made in this mood yet.",
    "History_Busy": "A wallpaper is being made. Try again when it's done.",
    "History_NoImage": "The picture of {0} isn't on disk any more (the storage limit removed it).",
    "History_MakingEcho": "Making an echo of {0}…",
    "History_Deleted": "Deleted {0}.",
    "Lineage_Title": "Original and echoes",
    "Lineage_Original": "Original",
    "Lineage_Echo": "Echo",
    "Lineage_ListName": "Original and echoes of {0}",
    "Lineage_NoneNow": "This wallpaper has no echoes any more.",
    "Delete_Title": "Delete “{0}”?",
    "Delete_Body": "Its image is deleted and AutoPaper forgets it, so a similar idea may come back. Echoes of it stay.",
    "Delete_Confirm": "Delete",

    # ── Settings home ──
    "SettingsTitle.Text": "Settings",
    "Settings_Title": "Settings",
    "Pane_General": "General",
    "Pane_Providers": "Providers",
    "Pane_Keys": "Keys",
    "Pane_Memory": "Memory",
    "Pane_Budget": "Budget",
    "Pane_About": "About",
    "PaneGeneralCard.Header": "General",
    "PaneGeneralCard.Description": "Schedule, pause, your own wallpaper, lock screen, sign-in and notifications",
    "PaneProvidersCard.Header": "Providers",
    "PaneProvidersCard.Description": "Who writes the ideas and who paints them",
    "PaneKeysCard.Header": "Keys",
    "PaneKeysCard.Description": "API keys for OpenAI, Google Gemini and OpenAI-compatible servers",
    "PaneMemoryCard.Header": "Memory",
    "PaneMemoryCard.Description": "Quiet period, echoes, what it has learned, and storage",
    "PaneBudgetCard.Header": "Budget",
    "PaneBudgetCard.Description": "Monthly limit and estimated costs",
    "PaneAboutCard.Header": "About",
    "PaneAboutCard.Description": "Version, licence and links",

    # ── General ──
    "GeneralCadence.Header": "New wallpaper",
    f"GeneralCadence.{NAME}": "New wallpaper",
    "GeneralCadence.Description": "How often AutoPaper makes a new one.",
    "Cadence_Hourly": "Every hour",
    "Cadence_Every3Hours": "Every 3 hours",
    "Cadence_Every6Hours": "Every 6 hours",
    "Cadence_Every12Hours": "Every 12 hours",
    "Cadence_Daily": "Every day",
    "Cadence_Weekly": "Every week",
    "Cadence_Manual": "Only when I ask",
    "GeneralPause.Header": "Pause new wallpapers",
    f"GeneralPause.{NAME}": "Pause new wallpapers",
    "GeneralPause.Description": "No new ones on the schedule until you turn this off. The current wallpaper stays, and New wallpaper now still works.",
    # The person's own wallpaper and lock screen (docs/app-spec.md 3a): kept, and put back on quit or here. Pausing
    # keeps AutoPaper's current wallpaper (user, 2026-10-06).
    "GeneralOwnWallpaper.Header": "Your own wallpaper",
    f"GeneralOwnWallpaper.{NAME}": "Your own wallpaper",
    "GeneralRestoreWallpaper.Content": "Restore my wallpaper",
    "OwnWallpaper_Description": "AutoPaper keeps a copy of your own wallpaper and lock screen, and puts them back when it quits or when you choose Restore my wallpaper. Pausing keeps the current wallpaper.",
    "OwnWallpaper_Showing": "Your own wallpaper is on the desktop. AutoPaper's next new wallpaper replaces it.",
    "OwnWallpaper_Restored": "Your own wallpaper is back on the desktop.",
    "OwnWallpaper_RestoreFailed": "Windows didn't put your own wallpaper back. Try again in a moment.",
    "OwnWallpaper_RestoredSpotlight": "Your own wallpaper is back on the desktop, as the last picture Windows Spotlight showed. Spotlight itself is off.",
    "OwnWallpaper_SpotlightOff": "Your Windows Spotlight background is back as the last picture it showed. Windows doesn't let apps turn Spotlight on, so it stays off until you turn it back on.",
    "GeneralSpotlightLink.Content": "Turn Windows Spotlight back on",
    "Spotlight_TurnOn": "Turn Windows Spotlight back on",
    # The person's own lock screen, put back on quit and Restore my wallpaper; what Windows doesn't let an app put back
    # is said, with the link to Windows' lock screen settings.
    "OwnLockScreen_Restored": "Your own lock screen is back.",
    "OwnLockScreen_Spotlight": "Windows Spotlight was your lock screen. Windows doesn't let apps turn it back on.",
    "OwnLockScreen_Slideshow": "A slideshow was your lock screen. Windows doesn't let apps turn it back on.",
    "OwnLockScreen_Unreadable": "Windows didn't let AutoPaper read your own lock screen picture, so it couldn't put it back.",
    "OwnLockScreen_Failed": "Windows didn't take your own lock screen picture back.",
    "OwnLockScreen_TurnOnSpotlight": "Turn Windows Spotlight back on for the lock screen",
    "OwnLockScreen_TurnOnSlideshow": "Turn your lock screen slideshow back on",
    "OwnLockScreen_Choose": "Choose your lock screen picture again",
    "GeneralLockScreen.Header": "Also set the lock screen",
    f"GeneralLockScreen.{NAME}": "Also set the lock screen",
    "GeneralLockScreen.Description": "The lock screen shows the same wallpaper.",
    "LockScreen_Description": "The lock screen shows the same wallpaper. Quitting AutoPaper and Restore my wallpaper put your own back.",
    "LockScreen_SpotlightCaveat": "Your lock screen uses Windows Spotlight, which only you can turn back on once AutoPaper changes it.",
    "LockScreen_SlideshowCaveat": "Your lock screen is a slideshow, which only you can turn back on once AutoPaper changes it.",
    "LockScreen_ManagedSetting": "Your organisation manages the lock screen on this PC, so AutoPaper can't change it.",
    "LockScreen_MaybeUnsupported": "Windows may not let apps change the lock screen on this PC. AutoPaper tries, and says if it can't.",
    "LockScreen_Managed": "AutoPaper couldn't set the lock screen: it's managed by your organisation on this PC.",
    "LockScreen_Failed": "Windows didn't let AutoPaper change the lock screen this time. The desktop has the new wallpaper.",
    "GeneralReplaceDisliked.Header": "Replace wallpapers I dislike",
    f"GeneralReplaceDisliked.{NAME}": "Replace wallpapers I dislike",
    "GeneralReplaceDisliked.Description": "Makes a new one straight away when you dislike the one showing, if the budget allows.",
    "GeneralFallback.Header": "When a new one can't be made",
    f"GeneralFallback.{NAME}": "When a new one can't be made",
    "GeneralFallback.Description": "Service checks that fail show the latest saved wallpaper from the current mood. Budget blocks keep the current wallpaper. This choice applies to other scheduled failures.",
    "FallbackRevisit.Content": "Bring back one I liked",
    "FallbackKeep.Content": "Keep the current one",
    "GeneralWindowsSection.Text": "Windows",
    "GeneralSignIn.Header": "Open AutoPaper when I sign in",
    f"GeneralSignIn.{NAME}": "Open AutoPaper when I sign in",
    "SignIn_Description": "Starts in the notification area, ready to make new wallpapers.",
    "SignIn_DisabledByUser": "Turned off in Windows Settings > Apps > Startup. Turn it on there to use this.",
    "SignIn_Policy": "Your organisation manages this setting.",
    "GeneralStartupAppsLink.Content": "Open Startup apps in Windows Settings",
    "GeneralNotify.Header": "Notify me about new wallpapers",
    f"GeneralNotify.{NAME}": "Notify me about new wallpapers",
    "GeneralNotify.Description": "With Like and Dislike buttons. Never for routine problems.",
    "GeneralNotificationSettingsLink.Content": "Notification settings in Windows",

    # ── Providers ──
    "ProvidersIntro.Text": "AutoPaper asks one AI to write each idea and one to paint it. Only your keywords and the composed prompt are sent, and only to the providers you choose.",
    "GeminiNote.Title": "About free Gemini keys",
    "GeminiNote.Message": "A free Gemini key may let Google use what you send to improve its products; a paid project doesn't.",
    "GeminiNoteShort.Text": "A free Gemini key may let Google use what you send to improve its products; a paid project doesn't.",
    "ProvidersWritingSection.Text": "Writing ideas",
    "ProvidersWritingKind.Header": "Writer",
    f"ProvidersWritingKind.{NAME}": "Writer",
    "ProvidersWritingKind.Description": "Turns your keywords into a scene to paint.",
    "ProvidersPaintingSection.Text": "Painting",
    "ProvidersPaintingKind.Header": "Painter",
    f"ProvidersPaintingKind.{NAME}": "Painter",
    "ProvidersPaintingKind.Description": "Paints the scene.",
    "ProviderAddress.Header": "Server address",
    "Address_LocalDescription": "Leave empty for the usual address on this PC.",
    "Address_CompatibleDescription": "The server's address, for example LM Studio's.",
    "Address_CompatiblePlaceholder": "For example, http://127.0.0.1:1234",
    "ProviderModel.Header": "Model",
    "Models_Default": "Default",
    # The model picker's blank choice, named from the core's default_model(kind, job).
    "Models_DefaultNamed": "Default ({0})",
    "Models_DefaultFirst": "Default (the server's first model)",
    "Models_Listed": "{0} available.",
    "Models_NoneListed": "The provider didn't list any models. Default uses its own choice.",
    "Models_Listing": "Looking for models…",
    "Models_NeedAddress": "Enter the server's address above, and its models appear here.",
    f"TextModelBox.{NAME}": "Model for writing ideas",
    f"ImageModelBox.{NAME}": "Model for painting",
    f"TextRefresh.{NAME}": "Refresh models for writing ideas",
    f"TextRefresh.{TIP}": "Refresh models",
    f"ImageRefresh.{NAME}": "Refresh models for painting",
    f"ImageRefresh.{TIP}": "Refresh models",
    "TextTestButton.Content": "Test",
    f"TextTestButton.{NAME}": "Test the writer",
    "ImageTestButton.Content": "Test",
    f"ImageTestButton.{NAME}": "Test the painter",
    "ProviderQuality.Header": "Painting quality",
    f"ProviderQuality.{NAME}": "Painting quality",
    "ProviderQuality.Description": "High costs more with OpenAI and Gemini.",
    "QualityStandard.Content": "Standard",
    "QualityHigh.Content": "High",
    "ProviderWorkflow.Header": "Workflow",
    f"ProviderWorkflow.{NAME}": "ComfyUI workflow",
    "WorkflowAutoPaper.Content": "AutoPaper's",
    "WorkflowOwn.Content": "Your own…",
    "Workflow_AutoPaperDescription": "The Model menu lists the models you have installed that AutoPaper has a tested workflow for.",
    "Workflow_OwnDescription": "A workflow you exported from ComfyUI in API format, with {{prompt}}, {{width}}, {{height}} and {{seed}} where AutoPaper fills them in.",
    "ProviderWorkflowFile.Header": "Workflow file",
    f"ProviderWorkflowFile.{NAME}": "Workflow file",
    "ProviderWorkflowChoose.Content": "Choose another…",
    "Workflow_OwnUnnamed": "Your own workflow",
    "Workflow_ModelLine": "{0} (from your workflow)",
    "Workflow_ModelLineSpoken": "Model: {0}",
    "Workflow_ModelUnknown": "Set in your workflow",
    "Workflow_Using": "Using your workflow, {0}.",
    "Workflow_UsingAutoPaper": "Using AutoPaper's workflows.",
    "Workflow_NotJson": "That file isn't a ComfyUI workflow in API format (JSON).",
    "ProviderTest.Header": "Test",
    "Test_Description": "Checks the address, the key and the model list with a small request.",
    "Test_Running": "Testing…",
    "Test_Ok": "{0} answered. It's ready to use.",
    # How long a model takes on this PC (estimate), on its card: "About 9 minutes per wallpaper on this PC."
    "Estimate_PerWallpaper": "{0} per wallpaper on this PC.",
    "Estimate_PerIdea": "{0} per idea on this PC.",
    # The provider cards' spoken names (both jobs share their headers).
    "Card_AddressWriter": "Server address for writing ideas",
    "Card_AddressPainter": "Server address for painting",
    "Card_ModelWriter": "Model for writing ideas",
    "Card_ModelPainter": "Model for painting",
    "Card_TestWriter": "Test the writer",
    "Card_TestPainter": "Test the painter",
    "Install_OllamaHeader": "Get Ollama for Windows",
    "Install_OllamaDescription": "Not installed? Download it from ollama.com, or run winget install Ollama.Ollama in Terminal. Models are separate downloads.",
    "Install_ComfyHeader": "Get ComfyUI Desktop for Windows",
    "Install_ComfyDescription": "Not installed? Download ComfyUI Desktop from comfy.org. Models are separate downloads.",
    "Install_OpenInBrowser": "Opens in your browser",
    "Install_NotRunning": "{0} isn't running at {1}. Start it, or install it with the link below.",
    "ProvidersKeysSection.Text": "Keys",
    "ProvidersKeysLink.Header": "API keys",
    "ProvidersKeysLink.Description": "OpenAI, Google Gemini and OpenAI-compatible servers",
    "Provider_Compatible": "OpenAI-compatible",
    "Provider_CompatibleInSentence": "The OpenAI-compatible server",
    "Provider_CompatibleSubject": "Your OpenAI-compatible server",
    "Provider_Demo": "Demo",
    "Provider_DemoOption": "Demo (no AI, gradients)",

    # ── Keys ──
    "KeysIntro.Text": "Keys save as you type, in Windows Credential Manager for your account on this PC. Each key is sent only to its own service.",
    "KeyOpenAi.Header": "OpenAI API key",
    f"KeyOpenAi.{NAME}": "OpenAI API key",
    f"KeyOpenAiBox.{NAME}": "OpenAI API key",
    "KeyOpenAiBox.PlaceholderText": "Paste your key",
    "KeyOpenAiGet.Content": "Get a key",
    "KeyGoogle.Header": "Google Gemini API key",
    f"KeyGoogle.{NAME}": "Google Gemini API key",
    f"KeyGoogleBox.{NAME}": "Google Gemini API key",
    "KeyGoogleBox.PlaceholderText": "Paste your key",
    "KeyGoogleGet.Content": "Get a key",
    "Key_NotSet": "Not set.",
    "Key_Saved": "Saved.",
    "Key_Removed": "Removed.",
    "Key_SavedSpoken": "{0}: {1}",
    "Key_SaveFailed": "Windows didn't save the key. Try again.",
    "Key_TooLong": "That key is too long for Windows Credential Manager. Check that it's only the key.",
    "KeysCompatibleSection.Text": "OpenAI-compatible servers",
    "KeysCompatibleNone.Text": "When you choose OpenAI-compatible in Providers, a key for that server appears here.",
    "Key_ForServer": "Key for {0}",
    "Key_ServerOptional": "Only if the server asks for one. It's sent only to this address.",

    # ── Memory ──
    "MemoryQuiet.Header": "Quiet period",
    f"MemoryQuiet.{NAME}": "Quiet period",
    "MemoryQuiet.Description": "How long before AutoPaper may come back to a similar idea.",
    "Quiet_OneMonth": "1 month",
    "Quiet_ThreeMonths": "3 months",
    "Quiet_SixMonths": "6 months",
    "Quiet_OneYear": "1 year",
    "Quiet_TwoYears": "2 years",
    "MemoryEchoes.Header": "Echoes",
    f"MemoryEchoes.{NAME}": "Echoes",
    "MemoryEchoes.Description": "Now and then, an idea past its quiet period comes back as a new interpretation.",
    "Echoes_Off": "Off",
    "Echoes_Rarely": "Rarely",
    "Echoes_Sometimes": "Sometimes",
    "Echoes_Often": "Often",
    "MemoryStatus.Header": "Memory",
    f"MemoryStatus.{NAME}": "Memory",
    "Memory_Full": "Full memory ({0}): AutoPaper recognises ideas it has had before, even in other words.",
    "Memory_Reduced": "Reduced memory: AutoPaper only catches near-identical repeats, because its memory model couldn't be loaded.",
    # What AutoPaper has learned (taste_summary), shared by every mood.
    "LearnedTitle.Text": "What AutoPaper has learned",
    "LearnedLikedCard.Header": "You tend to like",
    f"LearnedLikedCard.{NAME}": "You tend to like",
    "LearnedDislikedCard.Header": "You tend to dislike",
    f"LearnedDislikedCard.{NAME}": "You tend to dislike",
    "LearnedEmpty.Text": "Nothing yet. Like or dislike a few wallpapers and AutoPaper learns what you enjoy.",
    "LearnedNone.Text": "Nothing yet",
    "MemoryStorageSection.Text": "Storage",
    "MemoryUsage.Header": "Images on disk",
    f"MemoryUsage.{NAME}": "Images on disk",
    "Memory_Usage": "{0}, {1}. Memory holds {2}.",
    "Count_ImageOne": "1 image",
    "Count_ImageMany": "{0} images",
    "Count_WallpaperOne": "1 wallpaper",
    "Count_WallpaperMany": "{0} wallpapers",
    "MemoryLimit.Header": "Keep up to",
    f"MemoryLimit.{NAME}": "Keep up to",
    "MemoryLimit.Description": "Older images beyond this are deleted, never liked ones or the one showing. Memory keeps every idea.",
    "MemoryClear.Header": "Clear history",
    f"MemoryClear.{NAME}": "Clear history",
    "MemoryClear.Description": "Deletes the images and empties History.",
    "MemoryClearButton.Content": "Clear history…",
    "MemoryConsoleHelp.Header": "Console and run history",
    "MemoryConsolePrivacy.Text": "Console records requests, model responses, retries and outcomes on this device. It keeps the newest 200 runs for up to 30 days. Copy or export a selected run for debugging; review its prompts before sharing. Clearing Console leaves wallpapers, memory, settings and spending in place.",
    "MemoryConsoleStatistics.Text": "The overview covers retained runs. Success rate and average run time include completed and failed runs; blocked, cancelled and interrupted runs remain separate outcomes. Daily bars use UTC dates. Model bars show average measured Writing or Painting call time and the number of completed calls linked to retained runs. Older, unlinked timings are not included.",
    "MemoryConsoleLegacy.Text": "Runs made before Console was added have no recorded request trace. Their saved image prompt is still available in History. Runs stopped before a model was contacted have no provider events.",
    "MemoryConsoleHelpLink.Content": "Console help",
    "ClearHistory_Title": "Clear history?",
    "ClearHistory_Body": "AutoPaper deletes every image and empties History. Keeping memory lets it still avoid repeating itself; clearing everything also forgets what it has learned. Keywords and settings stay.",
    "ClearHistory_KeepMemory": "Clear, keep memory",
    "ClearHistory_Everything": "Clear everything",
    "ClearHistory_DoneKept": "History cleared. Memory kept.",
    "ClearHistory_DoneAll": "History and memory cleared.",
    "MemoryResetLearned.Header": "Reset what it learned",
    f"MemoryResetLearned.{NAME}": "Reset what it learned",
    "MemoryResetLearned.Description": "Forgets the likes and dislikes learned from your ratings.",
    "MemoryResetLearnedButton.Content": "Reset…",
    "Size_Bytes": "{0} bytes",
    "Size_KB": "{0} KB",
    "Size_MB": "{0} MB",
    "Size_GB": "{0} GB",
    "Size_TB": "{0} TB",

    # ── Budget ──
    "BudgetMonthly.Header": "Monthly budget",
    f"BudgetMonthly.{NAME}": "Monthly budget",
    "BudgetMonthly.Description": "A new wallpaper is blocked when its estimated cost plus this month's spending would exceed the limit. The current wallpaper stays. Local providers and Demo are free.",
    f"BudgetBox.{NAME}": "Monthly budget",
    "Budget_NoLimitChoice": "No limit",
    "Budget_Custom": "Custom",
    "BudgetCustomCard.Header": "Custom amount",
    "BudgetCustomCard.Description": "In US dollars, from $1 to $1,000 a month.",
    f"BudgetCustomCard.{NAME}": "Custom amount",
    f"BudgetCustomBox.{NAME}": "Custom monthly budget, in US dollars",
    "BudgetCustomBox.PlaceholderText": "Dollars",
    "BudgetSpent.Header": "This month",
    f"BudgetSpent.{NAME}": "This month",
    "Budget_SpentDetail": "{0}, {1} made.",
    "BudgetEstimate.Header": "Estimated cost",
    f"BudgetEstimate.{NAME}": "Estimated cost",
    "Budget_EstimateDetail": "About {0} per wallpaper, and about {1} a month with a new one {2}.",
    "Budget_EstimateManual": "About {0} per wallpaper. New wallpapers come only when you ask, so the month is up to you.",
    "Budget_EstimateFree": "Free with the providers you've chosen.",
    "Budget_PricesAsOf": "Prices as of {0}. Estimates use each provider's published prices.",
    "Budget_OfLimit": "{0} of {1} this month (estimated)",
    "Budget_NoLimit": "{0} this month (estimated), no limit",
    "Money_UnderACent": "less than $0.01",

    # ── About ──
    "About_Version": "Version {0} ({1})",
    "AboutWebsite.Content": "Website",
    "AboutPrivacy.Content": "Privacy",
    "AboutHelp.Content": "Help",
    "AboutDescription.Text": "Tell your computer what you'd like to see. AutoPaper makes new wallpapers from a few keywords, with the AI you choose, and remembers what it has made.",

    # ── First run ──
    "FirstRunTitle.Text": "Welcome to AutoPaper",
    "FirstRunTagline.Text": "Tell your computer what you'd like to see.",
    "FirstRunStep1.Text": "1. Add a few keywords",
    "FirstRunStep1Body.Text": "Words for what you'd like to see, for example: rain, ruins, night, blue, peaceful. You can change them any time.",
    "FirstRunKeywordBox.PlaceholderText": "Add a keyword",
    f"FirstRunKeywordBox.{NAME}": "Add a keyword",
    "FirstRun_Added": "Your keywords: {0}",
    "FirstRunStep2.Text": "2. Choose who writes and paints",
    f"FirstRunWho.{NAME}": "Who writes and paints",
    "FirstRunOpenAi.Content": "OpenAI",
    "FirstRunGemini.Content": "Google Gemini",
    "FirstRunLocal.Content": "Local, on this PC (Ollama and ComfyUI)",
    "FirstRunDemo.Content": "Try it without AI",
    "FirstRun_Step3Key": "3. Add your key",
    "FirstRun_Step3Local": "3. Start Ollama and ComfyUI",
    "FirstRun_Step3Demo": "3. Nothing else to set up",
    "FirstRun_Step3OpenAiBody": "OpenAI writes and paints each wallpaper, and charges you for each one. Settings > Budget shows the estimates and keeps a monthly limit ($5 to start).",
    "FirstRun_Step3GeminiBody": "Google Gemini writes and paints each wallpaper, and charges you for each one. Settings > Budget shows the estimates and keeps a monthly limit ($5 to start).",
    "FirstRun_Step3LocalBody": "Free and private: Ollama writes the ideas and ComfyUI paints them, on this PC. Both need to be installed and running, each with a model.",
    "FirstRun_Step3DemoBody": "Demo paints soft gradients from your keywords, so you can try AutoPaper for free. Choose a real provider in Settings > Providers any time.",
    "FirstRun_OpenAiKey": "OpenAI API key",
    "FirstRun_GeminiKey": "Google Gemini API key",
    "FirstRun_GetOpenAiKey": "Get an OpenAI key",
    "FirstRun_GetGeminiKey": "Get a Gemini key",
    "FirstRunGetOllama.Content": "Get Ollama for Windows",
    "FirstRunGetComfy.Content": "Get ComfyUI Desktop for Windows",
    "FirstRunMake.Content": "Make my first wallpaper",
    "FirstRunSkip.Content": "Skip for now",

    # ── Errors (spec "Errors": a plain sentence per AutoPaperError) ──
    "Error_MissingKey": "Add your {0} key in Settings to start.",
    "Error_MissingKeyCompatible": "Add the key for your OpenAI-compatible server in Settings > Keys to start.",
    "Error_InvalidKey": "{0} didn't accept your key. Check it in Settings > Keys.",
    # ProviderUnavailable, by its typed reason. {0} is the provider as a subject ("ComfyUI", "Your OpenAI-compatible
    # server"). Then Error_TryLater on the schedule, or Error_TryAgain when the person asked just now.
    "Error_NotRunning": "{0} isn't answering. Check that it's running and its address is right.",
    "Error_NotRunningAt": "{0} isn't running at {1}.",
    "Error_TimedOut": "{0} took too long to answer.",
    "Error_ServerError": "{0} had a problem on its side.",
    "Error_Stopped": "The job was stopped in {0}.",
    "Error_Unavailable": "{0} isn't available right now.",
    "Error_TryLater": "AutoPaper will try again later.",
    "Error_TryAgain": "Try again in a moment.",
    "Error_RateLimited": "{0} asked AutoPaper to wait; it'll try again in {1} minutes.",
    "Error_RateLimitedOne": "{0} asked AutoPaper to wait; it'll try again in a minute.",
    "Error_Refused": "{0} declined to paint this idea; AutoPaper tried a gentler one.",
    "Error_UnsupportedImages": "{0} can't paint pictures. Choose another painter in Settings > Providers.",
    "Error_UnsupportedConcepts": "{0} can't write ideas. Choose another writer in Settings > Providers.",
    # With a link to the fix (docs/app-spec.md 6a): the sentence says what happened; the link where it's fixed.
    "Error_UnsupportedImagesShort": "{0} can't paint pictures.",
    "Error_UnsupportedConceptsShort": "{0} can't write ideas.",
    "Error_BudgetReachedShort": "The estimated next wallpaper would exceed this month's budget.",
    # PaintingFailed: the provider ran but couldn't paint (a ComfyUI node failed, no workflow for the model…). One
    # line and a link to Providers; never "try again later" (trying again on the timer can't fix it).
    "Error_PaintingFailed": "{0} couldn't paint with {1}.",
    "Error_PaintingFailedUnnamed": "{0} couldn't paint this wallpaper.",
    "Link_AddKey": "Add your {0} key",
    "Link_CheckKey": "Check your {0} key",
    "Link_AddServerKey": "Add your server's key",
    "Link_CheckServerKey": "Check your server's key",
    "Link_CheckSettings": "Check {0} settings",
    "Link_CheckServerSettings": "Check your server's settings",
    "Link_ChoosePainter": "Choose another painter",
    "Link_ChooseWriter": "Choose another writer",
    "Link_RaiseBudget": "Raise the budget",
    "Link_OpenMoods": "Open moods",
    "Link_OpenProviders": "Open provider settings",
    "Error_BudgetReached": "The estimated next wallpaper would exceed this month's budget. AutoPaper is keeping the current wallpaper until next month.",
    "Error_BudgetReachedKeep": "The estimated next wallpaper would exceed this month's budget. AutoPaper is keeping the current wallpaper until next month.",
    "Error_BudgetReachedManual": "The estimated next wallpaper would exceed this month's budget. The current wallpaper stays. You can raise the budget in Settings > Budget.",
    "Error_Offline": "AutoPaper can't reach the internet right now.",
    "Error_OfflineScheduled": "AutoPaper can't reach the internet right now; it'll try again later.",
    "Error_InvalidResponse": "The answer from your provider couldn't be used. Try again, or choose another model.",
    "Error_InvalidResponseScheduled": "The answer from your provider couldn't be used. AutoPaper will try again later.",
    # KeywordNotFollowed: one line that names the keyword, as a link that opens the mood (docs/app-spec.md 6a).
    "Error_KeywordLeftOut": "The writing model kept leaving out “{0}”.",
    "Error_KeywordIncluded": "The writing model kept including “{0}”, which this mood avoids.",
    # InvalidInput, by its typed reason (shown under the field it's about where there is one).
    "Invalid_KeywordEmpty": "A keyword needs at least one letter or number.",
    "Invalid_KeywordTooLong": "Keywords can be up to 40 characters.",
    "Invalid_TooManyKeywords": "You can have up to 64 keywords. Remove one to add another.",
    "Invalid_DuplicateKeyword": "Another keyword already has this text.",
    "Invalid_AddressMissing": "Enter the server's address.",
    "Invalid_AddressNotAllowed": "AutoPaper can't use that address. Use https, or http only for this PC or your local network, with no user name or password in it.",
    "Invalid_AddressInvalid": "That isn't a complete web address. Include http:// or https:// and the server's name.",
    "Invalid_NoModels": "The server has no models to use yet. Download one, then choose Refresh.",
    "Invalid_WorkflowNeedsPrompt": "Your ComfyUI workflow needs a {{prompt}} placeholder where AutoPaper puts the scene.",
    "Invalid_WorkflowNotApiFormat": "That workflow is in ComfyUI's editor format. In ComfyUI, choose Export (API) and use that file.",
    "Invalid_WorkflowInvalid": "Your ComfyUI workflow isn't valid once AutoPaper fills in {{prompt}}, {{width}}, {{height}} and {{seed}}. Check it in ComfyUI and export it again.",
    "Invalid_NothingToEcho": "Only a finished wallpaper can have an echo.",
    "Invalid_MoodNameEmpty": "A mood needs a name.",
    "Invalid_MoodNameTooLong": "Mood names can be up to 40 characters.",
    "Invalid_DuplicateMoodName": "Another mood already has this name.",
    "Invalid_LastMood": "There's always at least one mood, so the last one can't be deleted.",
    "Error_NotFound": "That wallpaper isn't in History any more.",
    "Error_NothingToRevisit": "There's no liked wallpaper to bring back yet.",
    "Error_Storage": "AutoPaper couldn't read or save its files. Check that the drive has space.",
    "Error_Internal": "Something went wrong inside AutoPaper. Try again.",
    "Error_Unexpected": "Something went wrong. Try again.",
    "Error_Open": "AutoPaper couldn't open its data. What went wrong is saved in its log, for support.",
    "Error_OpenStorage": "AutoPaper couldn't open its data. Check that the drive has space, then open AutoPaper again.",
    "Fatal_Title": "AutoPaper",
    "Fatal_Body": "AutoPaper couldn't start, so it will close. What went wrong is saved in its log, for support:\n{0}",
    "Revisit_OverBudget": "This month's budget is spent, so AutoPaper brought back one you liked.",
    "Revisit_Offline": "AutoPaper couldn't reach the internet, so it brought back one you liked.",
    "Revisit_ProviderFailed": "{0} couldn't make a new one, so AutoPaper brought back one you liked.",
    "Revisit_Requested": "Brought back from History.",
    "Revisit_ServicesUnavailable": "A writing or painting service is unavailable, so AutoPaper is showing the latest saved wallpaper from this mood. See Console for both service checks.",

    # ── Progress and status ──
    "Stage_CheckingServices": "Checking services…",
    "Stage_Composing": "Composing an idea…",
    "Stage_CheckingMemory": "Checking memory…",
    "Stage_Painting": "Painting…",
    "Stage_Downloading": "Downloading…",
    "Stage_Preparing": "Preparing for your displays…",
    "Stage_Cancelling": "Cancelling…",
    # The time left while painting (from the engine's progress detail): "{0}" is "about 6 minutes", "a few seconds".
    "TimeLeft_Left": "{0} left",
    "TimeLeft_AlmostDone": "Almost done",
    "Stage_WithTimeLeft": "{0} {1}",
    "Stage_AlmostDone": "{0} almost done",
    "Span_FewSeconds": "a few seconds",
    "Span_Seconds": "about {0} seconds",
    "Span_Minute": "about a minute",
    "Span_Minutes": "about {0} minutes",
    "Span_Hour": "about an hour",
    "Span_Hours": "about {0} hours",
    "Span_HourMinutes": "about 1 hour {1} minutes",
    "Span_HoursMinutes": "about {0} hours {1} minutes",
    "Status_Cancelled": "Cancelled.",
    "Status_CancelledKept": "Cancelled. It was already made, so it's in History; the desktop stays as it was.",
    "Status_TooLateToCancel": "It's already going on your desktop, so it can't be cancelled now.",
    "Status_NewWallpaper": "New wallpaper: {0}",
    "Status_ShowingNow": "Showing {0}.",
    "Status_Liked": "Liked.",
    "Status_Disliked": "Disliked.",
    "Status_RatingCleared": "Rating cleared.",
    "Next_Paused": "New wallpapers are paused.",
    "Next_Manual": "New wallpapers only when you ask.",
    "Next_Soon": "Next new wallpaper soon.",
    "Next_Today": "Next new wallpaper at {0}",
    "Next_Tomorrow": "Next new wallpaper tomorrow at {0}",
    "Next_Weekday": "Next new wallpaper on {0} at {1}",
    "Next_Date": "Next new wallpaper on {0} at {1}",
    "Rating_Liked": "Liked",
    "Rating_Disliked": "Disliked",

    # ── Notification-area menu (sentence case; Windows) ──
    "Menu_Like": "Like",
    "Menu_Mood": "Mood",
    "Menu_EditMoods": "Edit moods",
    "Menu_MoodActions": "Actions for this mood",
    "Menu_Dislike": "Dislike",
    "Menu_NewWallpaper": "New wallpaper now",
    "Menu_Cancel": "Cancel",
    "Menu_Pause": "Pause new wallpapers",
    "Menu_Resume": "Resume new wallpapers",
    "Menu_RestoreWallpaper": "Restore my wallpaper",
    "Menu_Show": "Show AutoPaper",
    "Menu_Settings": "Settings",
    "Menu_Help": "Help",
    "Menu_Quit": "Quit AutoPaper",
    "Menu_Opening": "Opening…",
    "Menu_WallpaperActions": "Actions for this wallpaper",
    "Menu_KeywordActions": "Actions for this keyword",

    # ── Notifications ──
    "Notification_NewWallpaper": "New wallpaper: {0}",
    "Notification_Like": "Like",
    "Notification_Dislike": "Dislike",
    "Notification_Show": "Show",
    "Notification_OpenBudget": "Open budget settings",
    "Notification_OpenKeys": "Open keys settings",
    "Notification_KeyBody": "New wallpapers wait until it works.",
    "Notification_ImageAlt": "Preview of {0}",
    "Notification_SpotlightTitle": "Windows Spotlight is off",
    "Notification_SpotlightBody": "AutoPaper put back the last picture Spotlight showed. Windows lets only you turn Spotlight back on.",
    "Notification_SpotlightBothTitle": "Windows Spotlight is off",
    "Notification_SpotlightBothBody": "AutoPaper put back your own wallpaper and lock screen. Windows lets only you turn Spotlight back on.",
    "Notification_LockSpotlightTitle": "Windows Spotlight is off on the lock screen",
    "Notification_LockSlideshowTitle": "Your lock screen slideshow is off",
    "Notification_LockSpotlightBody": "Windows lets only you turn it back on, in Lock screen settings.",
}

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by apps/windows/tools/strings.py: edit the strings there, then run it. -->
<root>
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
"""


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    body = "".join(
        f'  <data name="{escape(key, {chr(34): "&quot;"})}" xml:space="preserve"><value>{escape(value)}</value></data>\n'
        for key, value in S.items()
    )
    OUT.write_text(HEADER + body + "</root>\n", encoding="utf-8")
    print(f"{len(S)} strings → {OUT.relative_to(OUT.parents[4])}")


if __name__ == "__main__":
    main()
