#!/usr/bin/env python3
"""Regenerates the "Rust crates" part of THIRD-PARTY-NOTICES.md from Cargo.lock.

The crates are the ones compiled into what ships: the shared core (in every app) and the Linux app, for macOS,
Windows and Linux on x86_64 and ARM64. Build scripts' and tests' own dependencies are left out, and so are
AutoPaper's own crates. cargo-about (https://github.com/EmbarkStudios/cargo-about) reads the dependency graph and
each crate's licence files; this script turns its JSON into a table and the licence texts, and replaces what's
between the generated-section markers in THIRD-PARTY-NOTICES.md. Everything else in that file is written by hand.

Run it after anything changes Cargo.lock:

    brew install cargo-about                    # or: cargo install --locked cargo-about
    python3 scripts/third_party_notices.py      # rewrites the section
    python3 scripts/third_party_notices.py --check   # exits 1 if the section is out of date
"""
import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOTICES = ROOT / "THIRD-PARTY-NOTICES.md"
BEGIN = "<!-- BEGIN generated by scripts/third_party_notices.py: don't edit by hand -->"
END = "<!-- END generated by scripts/third_party_notices.py -->"
OWN = {"autopaper-core", "autopaper-linux", "autopaper-cli", "uniffi-bindgen"}

# Licences AutoPaper accepts, in order of preference: where a crate offers a choice ("MIT OR Apache-2.0"),
# cargo-about picks the first one listed here.
ACCEPTED = ["MIT", "Apache-2.0", "Apache-2.0 WITH LLVM-exception", "BSD-2-Clause", "BSD-3-Clause", "ISC", "Zlib",
            "Unicode-3.0", "MPL-2.0", "BSL-1.0", "0BSD", "MIT-0", "CC0-1.0", "Unlicense", "OpenSSL"]
TARGETS = ["aarch64-apple-darwin", "x86_64-apple-darwin", "aarch64-pc-windows-msvc", "x86_64-pc-windows-msvc",
           "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]


def cargo_about(manifest, config):
    result = subprocess.run(
        ["cargo-about", "generate", "--format", "json", "--locked", "--fail", "-c", str(config),
         "-m", str(ROOT / manifest)],
        cwd=ROOT, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(f"cargo-about failed for {manifest}:\n{result.stderr}")
    return json.loads(result.stdout)


def fence(text):
    """A code fence longer than any run of backticks in the text."""
    longest = max((len(run) for run in re.findall(r"`+", text)), default=0)
    return "`" * max(3, longest + 1)


def render(linux, core):
    in_core = {(c["package"]["name"], c["package"]["version"]) for c in core["crates"]}
    crates = sorted(
        {(c["package"]["name"], c["package"]["version"], c["license"]) for c in linux["crates"]
         if c["package"]["name"] not in OWN},
        key=lambda c: (c[0].lower(), c[1]))
    linux_only = sum(1 for name, version, _ in crates if (name, version) not in in_core)

    out = [
        BEGIN,
        "",
        f"{len(crates)} crates, as `Cargo.lock` pins them: {len(crates) - linux_only} in the shared core, which every "
        f"app includes, and {linux_only} more in the Linux app only. Generated with cargo-about "
        "(`python3 scripts/third_party_notices.py`), for macOS, Windows and Linux on x86_64 and ARM64; build "
        "scripts' and tests' own dependencies aren't shipped and aren't listed.",
        "",
        "| Crate | Version | Licence | In |",
        "|---|---|---|---|",
    ]
    for name, version, licence in crates:
        where = "every app" if (name, version) in in_core else "Linux app"
        out.append(f"| {name} | {version} | {licence} | {where} |")

    out += [
        "",
        "### Licence texts",
        "",
        "Each text once, with the crates it covers. Where a crate offers a choice of licences, the first of these "
        "is used: " + ", ".join(ACCEPTED) + ".",
        "",
    ]
    for group in linux["licenses"]:
        users = sorted({(u["crate"]["name"], u["crate"]["version"]) for u in group["used_by"]
                        if u["crate"]["name"] not in OWN}, key=lambda u: (u[0].lower(), u[1]))
        if not users:
            continue
        text = "\n".join(line.rstrip() for line in group["text"].strip("\n").splitlines())
        marks = fence(text)
        out += [f"**{group['name']}**, for " + ", ".join(f"{n} {v}" for n, v in users) + ":", "",
                marks + "text", text, marks, ""]
    out.append(END)
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if THIRD-PARTY-NOTICES.md is out of date")
    args = parser.parse_args()
    if not shutil.which("cargo-about"):
        sys.exit("cargo-about is needed: brew install cargo-about (or cargo install --locked cargo-about)")

    with tempfile.TemporaryDirectory() as tmp:
        config = Path(tmp) / "about.toml"
        config.write_text(
            f"accepted = {json.dumps(ACCEPTED)}\n"
            f"targets = {json.dumps(TARGETS)}\n"
            "ignore-build-dependencies = true\n"
            "ignore-dev-dependencies = true\n")
        # The Linux app depends on the core, so its graph is the core's plus the Linux app's own crates.
        linux = cargo_about("apps/linux/Cargo.toml", config)
        core = cargo_about("core/Cargo.toml", config)

    current = NOTICES.read_text()
    if BEGIN not in current or END not in current:
        sys.exit(f"{NOTICES.name} has no generated-section markers:\n{BEGIN}\n{END}")
    head, rest = current.split(BEGIN, 1)
    tail = rest.split(END, 1)[1]
    updated = head + render(linux, core) + tail
    if args.check:
        if updated != current:
            sys.exit(f"{NOTICES.name} is out of date: run python3 scripts/third_party_notices.py")
        print(f"{NOTICES.name} is up to date")
    elif updated != current:
        NOTICES.write_text(updated)
        print(f"Updated {NOTICES.name}")
    else:
        print(f"{NOTICES.name} was already up to date")


if __name__ == "__main__":
    main()
